### ISSUE TITLE
Is it possible to retrieve Appointments and Offers linked to a property?

### ISSUE THREAD

**Issue by mikemike** [dezrez/DezrezCoreAPI#14]
I'm trying to grab a list of entities attached to a property (as I only have a property ID), in this case it's Appointments and Offers.

I'm struggling to find the right API method for this on [Swagger](https://api.dezrez.com/swagger/ui/index), as everything there seems to require the specific entity ID in order to retrieve it (eg Appointment ID to get the appointment).

What I was hoping to find was something within Properties, such as:
GET /api/property/{id}/appointments
GET /api/property/{id}/offers

Which would return a list of linked appointment and offers objects.

Hopefully this is achievable.

Thanks

**Comment by marc-harry** [comment]
Hi @mikemike,

This is achievable, Instead of having specific endpoints for appointments, offers or any other event type we have a general events endpoint that takes an event type or event category to get a list of events that are related to a property. You could do the following for all events:
GET /api/property/{id}/events
Or for all offers:
GET /api/property/{id}/events?type=Offer

You can find a list of all event types by making a request to the enum endpoint like so:
GET /api/enum?typeName=EventType

You can then pass the SystemName as the type parameter to get events of just that type. We also have a wider grouping of events called event category and again you can get a list of the available ones through the enum endpoint passing EventCategory as the typeName parameter. You could then do:
GET /api/property/{id}/events?eventCategoryType=Appointment

Which would get you all events that are classified as being an appointment. You should be able to see what event category an event type is in the results from the call to the enum endpoint with typeName=EventType.

I hope this information helps.

Cheers,
Marc

**Comment by mikemike** [comment]
Hi @marc-harry 

Just what I was after.  Nice one, thanks.

Mike
