### ISSUE TITLE
"On Market"

### ISSUE THREAD

**Issue by ewanmceachran** [dezrez/DezrezCoreAPI#20]
Hi,

There are instances where a property has a selling role status of 'InstructionToSell' but there is no 'OnMarket' flag on the role. Perhaps there is a process that confirms a property as on market once it has been set to InstructionToSell?. But is there an event that can be picked up, that has made the OnMarket flag appear?

Thanks, Ewan

**Comment by rjmacarthy** [comment]
Hi @ewanmceachran a role can indeed have a status of `InstructionToSell` but may not have a flag set as `OnMarket`.  This data is still legitimate, a user can choose to "pause" a marketing role whilst preserving its  role status of `InstructionToSell`.

On the SPA the event on the `/api/role/{id}/Events` end point we look for is the compliance check:

```
      "EventType": {
        "Id": 143417,
        "Name": "Compliance Check",
        "SystemName": "ComplianceCheck"
      },
      "EventStatus": {
        "Id": 1996,
        "Name": "Completed",
        "SystemName": "Completed"
      }
```

As in order to add the `OnMarket` flag, the compliance checks must also exist.

This event will only ever show once in the role event history, so toggling the `OnMarket` flag via `api/role/{id}/setflag` endpoint wont continually add new events of this type.

It's worth noting that a role status of `InstructionToSell` may not have a `ComplicaneChecks` event as you can instruct a property without actually activating it's `OnMarket` status.

A role with `InstructionToSell` with no `OnMarket` flag will not display on portals, websites or in any live feed so should be treated as private in that sense.  Although by looking through the event history for that role, you will be able to determine the date, if at all that `OnMarket` flag was applied by looking for the `ComplianceCheck` event, as this is needed to actually set the flag in the first place.

It's also possible to have a `ComplicanceCheck` event but the property not have an `OnMarket` flag if the flag was removed after having being added previously.

Hope this makes some sort of sense.

Thanks.

Richard.

**Comment by ewanmceachran** [comment]
Thanks for that - a very full response. However, after yesterday (when I think you changed things on the server) I'm not getting any data back for the /api/role/{id}/Events call. For example:, to take a property that's currently showing as 'on market'

https://core-api-uat.dezrez.com/api/role/4712972/events?agencyID=125

returns

{"TotalCount":0,"CurrentCount":0,"PageSize":20,"PageNumber":1,"Collection":[]}

**Comment by rjmacarthy** [comment]
Hi @ewanmceachran we are currently working on UAT testing some critical changes.  Therefore, the data on UAT will be somewhat inconsistent for a few days while we iron things out.

Apologies for any inconvenience this causes.

Thanks.

Richard.
