### ISSUE TITLE
Create Viewing Request

### ISSUE THREAD

**Issue by dzy969** [dezrez/DezrezCoreAPI#36]
Hi,
Can you advise which API call(s) we should use to create a viewing request?

In the Rezi UI, under To-Dos, Unadssigned tasks, there is a queue for requests from 'online sources like websites and property portals'

We'd like to add viewing requests (and valuation requests) from our website to these todo queues

Thanks
Dean

**Comment by marc-harry** [comment]
Hi,
The best API endpoint to do this so that the requests end up in the todo queues is to use the `api/inboundlead/create` endpoint.

If you look at the data contract for this endpoint on the api help page you will see the structure for the request. The SourceType and RequestType properties on the data contract need to be filled in with one of the values return from the `api/enum/leadsourcetype` and `api/enum/leadrequesttype`. Request type will allow you to specify if its viewing or valuation. 

Currently there is no value in lead source type for third party app or for the app you are developing, but you could ask the agency your developing the app for to get in touch with us to add your app name as a lead source type and we can add this in manually for you to start using straight away.

Finally you will need to provide us with the Property Marketing Role Id for the property that the viewing or valuation request is for so that the details of the property appear correctly in the Rezi UI.

Cheers,
Marc

**Comment by prashant-v** [comment]
Hello,

Can you please specify more information about the following parameters in the API request?
assignToNegId - What Id do we need to pass, Is it mandatory field?
Email - what email address do we need to pass?

There are other fields in the request object, we have only SourceType, RequestType , peoples name and email and PropertyMarketingRoleIds field. Does this API will execute with all the above minimum fields.

Also we tried with passing the required fields but the API is returning below error message
{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"d7ee430d-f142-48d6-b5c3-209d067bc06a","Details":"Error occured whilst invoking action CreateLead on controller InboundLeadController. This error has been logged.","ValidationErrors":null}

Can you please guide for the same?

Thanks,
Nitin

**Comment by marc-harry** [comment]
Resolution in #37 is same for this

**Comment by prashant-v** [comment]
Thanks we are able to execute the API with following required parameters.
SourceType, RequestType, PropertyMarketingRoleIds, Email and DateSubmitted

Thanks,
Nitin
