### ISSUE TITLE
Create inboundlead TODO API issue

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#37]
Hello,

We are facing an issue in executing following API - https://core-api-uat.dezrez.com/Help/Api/POST-api-inboundlead-create_assignToNegId
We are getting an message :  Authorization has been denied for this request

Can you give us access of the same?

**Comment by marc-harry** [comment]
Hi @prashant-v,
We have set you up to be able to use the lead_sender claim, you will need to pass this as one of the scopes when you request an auth token. And then that endpoint will work.

Cheers,
Marc

**Comment by prashant-v** [comment]
Thanks, API is executing and we are facing following error.

{"Message":"Domain Service - Validation has failed for: InboundLeadsDomainService - CreateLead","ErrorReference":"ILDS-CL","Details":"See the ValidationErrors list of (1) issues for more details.","ValidationErrors":["No request type provided!"]}

Can you guide for the same?

**Comment by marc-harry** [comment]
You need to provide a DeterminedRequestType you can see all available request types by hitting the api/enum?typeName=LeadRequestType

Cheers,
Marc

**Comment by prashant-v** [comment]
Hello,

Can you please specify more information about the following parameters in the API request?
assignToNegId - What Id do we need to pass, Is it mandatory field?
Email - what email address do we need to pass?

There are other fields in the request object, we have only SourceType, RequestType , peoples name and email and PropertyMarketingRoleIds field. Does this API will execute with all the above minimum fields.

Also we tried with passing the required fields but the API is returning below error message
{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"d7ee430d-f142-48d6-b5c3-209d067bc06a","Details":"Error occured whilst invoking action CreateLead on controller InboundLeadController. This error has been logged.","ValidationErrors":null}

Can you please guide for the same?

Thanks,
Nitin

**Comment by marc-harry** [comment]
Hi @prashant-v,
The assignToNegId is an optional parameter if you know the negotiator Id the lead should be directed to then you can provide one but if not the lead is available to everyone in the branch to view.

The peoples names, RequestType and email should be the minimum yes, if the lead is anything other than general then yes the PropertyMarketingRoleIds field is also required.

The error that you are getting there appears to be due to a negotiator not being found with the Id provided was an Id provided to the assignToNegId parameter? If you don't need it to go to a specific person removing that from the request should result in it being successful.

Cheers,
Marc

**Comment by prashant-v** [comment]
Thanks we are able to execute API request.

Thanks,
Nitin
