### ISSUE TITLE
Possible issue trying to access private documents

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#44]
When I retrieve all documents for a property some are private and some are public. If I try and download the file of a private file I get the following error:

http://imgur.com/GnyPQ3Z

Is this a bug or is there another way to download a private file?

**Comment by dendle** [comment]
Hello Geoff,

You're seeing the raw error there, which is a bug; you should have a nice "Access Denied" error message there instead.

The term Private Documents means that these documents should not be made available in the public domain, so you are required to add the appropriate security headers to the request, as per calls to the main API - if you normally need to attach an agencyID to your API requests, you'll need to do that here, too.

If you are doing this and still get an error, please let us know.

In the meantime, i'll try to get that error message working so that you get meaningful responses for these exceptions.

Cheers,
Matt
