### ISSUE TITLE
Error in executing api/region/suggest API

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#57]
Hello,

We are trying to use api/region/suggest (https://core-api-uat.dezrez.com/Help/Api/POST-api-region-suggest) API to get available region in REZI, but we are facing 401 Unauthorized error.

We also cross checked for available scope but do not found any scope related to region. Can you please suggest solution for the same.

Please note we are facing the same issue while using another region related API which is api/region/favourites (https://core-api-uat.dezrez.com/Help/Api/GET-api-region-favourites) to get favourite regions

Thanks

**Comment by marc-harry** [comment]
Hi @prashant-v 

We have found the issue is with the permissions for those region endpoints, we have amended this now so they will work off the property_read and property_write scopes. The deployment is currently going through testing and then to the UAT environment and should be there in approximately one hours time.
