### ISSUE TITLE
Problem Reading Room Descriptions

### ISSUE THREAD

**Issue by neilrbanks** [dezrez/DezrezCoreAPI#60]
Hi 

We have an issue using 

https://api.dezrez.com/api/property/xxxxxx/descriptions/?agencyId=xx

Most properties are coming back with a room sequence containing a list of room descriptions but a number of properties do not contain the room descriptions even though there are room descriptions entered on the property example ids

736206
741305
743609
746007
749603
754507
766201

Thanks

**Comment by dendle** [comment]
Hello Neil,

The URL you mention queries descriptions from a property - these descriptions may or may not be used by related sales/lettings roles.

In the example you have given, property 736206 has a lettings role 5082034. The software itself is querying the descriptions in the lettings role rather than on the "parent" property.

The endpoint to get the descriptions for a role is:
https://api.dezrez.com/api/role/5082034/descriptions

I can confirm the rooms are in there.

Usually, the descriptions on a role would normally appear on a property, but this is not always the case, as is the case here.

In order to best follow the experience in the software, i'd use the endpoint I mention here.  Also the property description endpoint you mentioned may have duplicate/similar descriptions, as this is a collection of descriptions that are shared (for re-use) amoungst all roles for that property (to save the agent typing them again).

I hope this makes sense.

Kind Regards,
Matt

**Comment by neilrbanks** [comment]
Hi Matt

Thanks for response yes that make sense I will amend the code to pull descriptions from the properties appropriate role instead

Thanks Neil

**Comment by neilrbanks** [comment]
Thanks that makes sense
