### ISSUE TITLE
Cannot get Chain Data

### ISSUE THREAD

**Issue by tom-sinclair** [dezrez/DezrezCoreAPI#67]
It has been explained to me that in order for me to see the chain data I need to hit [this endpoint](https://core-api-uat.dezrez.com/swagger/ui/index#!/ProgressionChain/ProgressionChain_Get) and the ID I need is the purchasing role ID, and to get that I have to:
* search for a property
* find the attached marketing role to the property
* find the progression role attached to the marketing role
* find the purchasing role attached to the progression role
Then use the purchasing role ID to get the chain data for a property? Is that correct?
 
I can't find a property in UAT that has a marketing role, they are all either sales or letting. Could you point me to a property that has the marketing role and subsequent roles attached so I can write a chain integration, and if one does not exist can you create one for me to test with?

Secondly, is it right to assume that if this marketing role does not exist then the property is not in a chain as far you know?

Is there a quicker way to get the chain data for a property?

My agency ID is 4.

**Comment by ajonesgh** [comment]
Hi Tom

In order to add a chain the marketing role has to have a role status of offer accepted. 

Example below
GET https://core-api-uat.dezrez.com/api/property/1005801
GET https://core-api-uat.dezrez.com/api/role/11275403 <- Marketing Role e.g Selling or Letting
GET https://core-api-uat.dezrez.com/api/role/11510701 <- Purchasing Role

**Creating a new chain** 

Step 1. Create a chain
https://core-api-uat.dezrez.com/Help/Api/POST-api-progressionchain-id-createchain

Step 2.  Add Chain Node or Link
https://core-api-uat.dezrez.com/Help/Api/POST-api-progressionchain-id-addchainlink
https://core-api-uat.dezrez.com/Help/Api/POST-api-progressionchain-id-addchainnode

Spet 3. Get Chain
https://core-api-uat.dezrez.com/Help/Api/GET-api-progressionchain-id-getchain

Hope this helps

Thanks
Adam

**Comment by tom-sinclair** [comment]
Hi Adam,

I can get the purchasing role id from your above example, however when I use it to get the chain, the first endpoint, `/api/progressionchain/{id}/getchain` returns this error message to me: `Authorization has been denied for this request.` and the other endpoint `/api/progressionchain/{id}` returns an empty array, so I assume for the second endpoint it means there is no chain information, do you have an example of a property with a chain? Also, please confirm which endpoint I should be using.

Thanks

Tom
